services:
    collector:
      image: otel/opentelemetry-collector-contrib:0.72.0
      command: ["--config=/etc/otel-collector-config.yaml", ""]
      environment:
        - HONEYCOMB_APIKEY=${HONEYCOMB_APIKEY}
        - HONEYCOMB_SERVICENAME=${HONEYCOMB_SERVICENAME}
        - HONEYCOMB_METRICS_DATASET=${HONEYCOMB_METRICS_DATASET}
      volumes:
        - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      ports:
        - "1888:1888"   # pprof extension
        - "8888:8888"   # Prometheus metrics exposed by the collector
        - "8889:8889"   # Prometheus exporter metrics
        - "13133:13133" # health_check extension
        - "4317:4317"        # OTLP gRPC receiver
        - "4318:4318"        # OTLP http receiver
        - "6831:6831"        # thrift compact
        - "55670:55679" # zpages extension
      networks:
        - service_bridge  
  
networks:
  service_bridge:
    driver: bridge
