FROM ubuntu:22.04 AS BUILD

RUN apt update && apt install --no-install-recommends curl g++ gcc make cmake -y \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /scratch
ONBUILD COPY src src
ONBUILD COPY makefile makefile
ONBUILD RUN make

