FROM ubuntu:22.04 AS BUILD

ARG MAKE_TARGET=all
ARG MAKE_OPTIONS=-B

RUN apt update && apt install --no-install-recommends curl g++ gcc make cmake -y \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /scratch
ONBUILD COPY src src
ONBUILD COPY makefile makefile
ONBUILD RUN make ${MAKE_OPTIONS} ${MAKE_TARGET}

