# syntax=docker/dockerfile:1.4
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /scratch
# NOTE: Escape the \$ otherwise they are rendered at buildtime
COPY --chmod=755 <<EOF /bin/echoout.sh
#!/usr/bin/env bash
cat /scratch/README.md
EOF

# NOTE: This is not required as there is an undocumented flag --chmod
#RUN chmod +x /bin/ping.sh

ENTRYPOINT ["/bin/echoout.sh"]
CMD [""]