services:
    
  code:
    image: alpine:3.13

    volumes:
      - /usr/share/nginx/html
      - /code
      
    profiles: [all, code]

  nginx:
    image: nginx:1.21.1 

    ports:
      - 8080:80

    depends_on:
      - code

    volumes_from:
      - code:/usr/share/nginx/html
      - code:/code

    profiles: [all, frontend]