receivers:
  # prometheus:
  #   config:
  #     scrape_configs:
  #       - job_name: "prometheus"
  #         honor_timestamps: true
  #         scrape_interval: 15s
  #         scrape_timeout: 10s
  #         metrics_path: /metrics
  #         scheme: http
  #         static_configs:          
  #           - targets: ["${PROMETHEUS_COLLECTOR_TARGET}"] # this is the endpoint to scrape

  # hostmetrics:
  #   scrapers:
  #     cpu:
  #     disk:
  #     filesystem:
  #     load:
  #     memory:
  #     network:
  #     process:
  #     processes:
  #     paging:

  otlp:
    protocols:
      grpc: # on port 4317

  jaeger:
    protocols:
      thrift_compact:
        endpoint: 0.0.0.0:6831

processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_APIKEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_SERVICENAME}"

  # otlp/metrics:
  #   endpoint: "api.honeycomb.io:443"
  #   headers:
  #     "x-honeycomb-team": "${HONEYCOMB_APIKEY}"
  #     "x-honeycomb-dataset": "${HONEYCOMB_METRICS_DATASET}"

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [otlp]

    # metrics:
    #   receivers: [hostmetrics,prometheus]
    #   processors: []
    #   exporters: [otlp/metrics]

  telemetry:
    logs:
      level: "debug"
