set dotenv-load := true

# default lists actions
default:
  @just -f example.justfile --list

build-normal:
  #!/usr/bin/env bash
  set -eufo pipefail

  docker buildx build -f Dockerfile -t debug-build:latest .

build-debug:
  #!/usr/bin/env bash
  set -eufo pipefail

  BUILDX_EXPERIMENTAL=1 docker buildx dap build .

