set dotenv-load := true

ISNIXOS:=env_var_or_default('NIX_PATH', 'default_value')
# nixos (CDI)
#export NO_CACHE:="--no-cache"
export NO_CACHE:=""
export GPU_SHARE:=if "$ISNIXOS" == "default_value" {
  "--gpus all"
} else {
  "--device=nvidia.com/gpu=all"
}

# default lists actions
default:
  @just -f example.justfile --list

# can be applied anytime
sanity: 
  #!/usr/bin/env bash
  set -eufo pipefail
  docker pull nvidia/cuda:12.5.0-runtime-ubuntu22.04
  docker run ${GPU_SHARE} --rm docker.io/nvidia/cuda:12.5.0-runtime-ubuntu22.04  

details:
  #!/usr/bin/env bash
  set -xeufo pipefail
  docker build ${NO_CACHE} --progress=plain -f Dockerfile.details -t a2_gpu .
  docker run ${GPU_SHARE} --rm a2_gpu

cuda:
  #!/usr/bin/env bash
  set -eufo pipefail
  docker build ${NO_CACHE} --progress=plain -f Dockerfile.nvcc -t a2_gpu_nvcc .
  docker run ${GPU_SHARE} --rm a2_gpu_nvcc

compose-up:
  docker compose up 
 
compose-down:
  docker compose down

compose-ps:
  docker compose ps 

compose-shell service='sanity':
  docker compose exec -it {{ service }} bash

compose-logs service='sanity':
  docker compose logs {{ service }} 
