set dotenv-load := true

# default lists actions
default:
  @just -f example.justfile --list

nix:
  #!/usr/bin/env bash
  set -eufo pipefail
  nix develop --command zsh

distrobox-create:
  #!/usr/bin/env bash
  set -eufo pipefail
  distrobox create --name archlinux --init --image archlinux:latest
