FROM nginx:latest
#COPY ./cert.pem /etc/nginx/conf.d/cert.pem
#COPY ./key.pem /etc/nginx/conf.d/key.pem

COPY ./certs/testsite.local.crt /etc/nginx/conf.d/cert.pem
COPY ./certs/testsite.local.key /etc/nginx/conf.d/key.pem

COPY ./nginx_ssl.conf /etc/nginx/conf.d/default.conf
COPY ./site/img /usr/share/nginx/html/img
COPY ./site/js /usr/share/nginx/html/js
COPY ./site/favicon.ico /usr/share/nginx/html/favicon.ico
COPY ./site/index.html /usr/share/nginx/html/index.html
