apiVersion: skaffold/v2beta29 
kind: Config
metadata:
  name: -skaffold
build:
  artifacts:
  - image: skaffoldtest
    context: ./shellscript
    docker:
      dockerfile: ./Dockerfile
# local:
#   push: false
# deploy:
#   kubectl:
#     manifests:
#     - deployment.yaml