package:
  name: curl
  version: 8.7.1
  epoch: 0
  description: "URL retrieval utility and library"
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
      - https://packages.wolfi.dev/os
      - '@local /work/packages'
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub      
    packages:
      - brotli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - libpsl-dev
      - nghttp2-dev
      - openssl-dev
      - perl
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://curl.se/download/curl-${{package.version}}.tar.xz
      expected-sha256: 6fea2aac6a4610fbd0400afb0bcddbe7258a64c63f1f68e5855ebc0c659710cd

  - uses: autoconf/configure
    with:
      # https://everything.curl.dev/build/deps#libpsl
      opts: |
        --enable-ipv6 \
        --enable-unix-sockets \
        --with-openssl \
        --without-rustls \
        --with-nghttp2 \
        --with-pic \
        --disable-ldap \
        --without-libssh2 \
        --with-libpsl

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "curl-dev"
    description: "headers for libcurl"
    pipeline:
      - uses: split/dev

  - name: "curl-doc"
    description: "documentation for curl"
    pipeline:
      - uses: split/manpages

  - name: "libcurl-openssl4"
    description: "curl library (openssl backend)"
    dependencies:
      # raise the priority here so this beats rustls
      # TODO: revert this to "5" once rustls is fixed.
      provider-priority: 15
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libcurl.so.* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  version-separator: _
  github:
    identifier: curl/curl
    strip-prefix: curl-

test:
  pipeline:
    - runs: |
        curl --version
        curl -v https://example.com
