#!/usr/bin/env bash

function map-pipe {
    echo "# BRANCH is set to ${BRANCH}"
    echo "# COMMIT_SHA1 is set to ${COMMIT_SHA1}"
    echo ""

    # find env variables that start with branch and commitid
    while IFS='=' read -r var value 
    do
        if [[ -n "${BRANCH}" ]]; then 
            if [[ $var =~ ^${BRANCH} ]]; then
                local prefix=${BRANCH}_
                local name="${var/${prefix}/}" 
                echo "# FROM ${var}=${value}"
                echo "export ${name}=\"${value}\""
            fi
        fi
        if [[ -n "${COMMIT_SHA1}" ]]; then 
            if [[ $var =~ ^${COMMIT_SHA1} ]]; then
                local prefix=${COMMIT_SHA1}_
                local name="${var/${prefix}/}" 
                echo "# FROM ${var}=${value}"
                echo "export ${name}=\"${value}\""
            fi
        fi
    done
}

function map {
    echo "# BRANCH is set to ${BRANCH}"
    echo "# COMMIT_SHA1 is set to ${COMMIT_SHA1}"
    echo ""

    # find env variables that start with branch and commitid
    if [[ -n "${BRANCH}" ]]; then 
        while IFS='=' read -r var value 
        do
            local prefix=${BRANCH}_
            local name="${var/${prefix}/}" 
            echo "# FROM ${var}=${value}"
            echo "export ${name}=\"${value}\""
        done < <(env | grep ^${BRANCH})
    fi
    if [[ -n "${COMMIT_SHA1}" ]]; then 
        while IFS='=' read -r var value 
        do
            local prefix=${COMMIT_SHA1}_
            local name="${var/${prefix}/}" 
            echo "# FROM ${var}=${value}"
            echo "export ${name}=\"${value}\""
        done < <(env | grep ^${COMMIT_SHA1})
    fi
    #env
}

if [[ $1 == "--stdin" ]]; then
    map-pipe
else
    map 
fi

exit 0
