services:
    nginx:
        image: "nginx:1.20.1"
        environment:
            - VERSION=nginx:1.20.1
            - ANOTHER_VALUE1=ANOTHER_VALUE1
            - ANOTHER_VALUE2=ANOTHER_VALUE2
            - ANOTHER_VALUE3=ANOTHER_VALUE3
            - ANOTHER_VALUE4=ANOTHER_VALUE4
        ports:
            - "8080:80"
        networks:
            - service_bridge
        profiles: [all]


volumes:
    68_composing_services:

networks:
    service_bridge:
        driver: bridge

