# syntax=docker/dockerfile:1.4
FROM ubuntu:22.04 as BASE

RUN apt update && apt install -y cowsay \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /scratch
COPY hello1.txt ./hello1.txt

COPY --from=context2 hello2.txt ./hello2.txt

# NOTE: Escape the \$ otherwise they are rendered at buildtime
COPY <<EOF /scratch/run.sh
#!/usr/bin/env bash
/usr/games/cowsay "$(cat \$1)"
EOF
RUN chmod +x /scratch/run.sh

CMD ["/scratch/run.sh", "/scratch/hello2.txt"]


